application:
  port: 5555
poster_client:
  base_url: "http://localhost:6969"
  path: "latest"
user_client:
  base_url: "http://193.107.20.225:8080"
  count_path: "followees/count"
  fetch_path: "followees"